[workspace]
resolver = "2"
members = [
    # Battle Engine
    "crates/poke_engine",
    "crates/test_runner",
]

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"