[package]
name = "poke_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = "0.18.0"
bitflags = "2.4"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
heck = "0.4"
quote = "1.0"
proc-macro2 = "1.0"
